
Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.

In [15]:
import numpy as np

vector = np.arange(1, 21)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.

In [16]:
import numpy as np

mat = np.ones((4, 4), dtype=int)
print(mat)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.

In [17]:
import numpy as np

array = np.random.uniform(-1, 1, size=(5, 5))
print(array)

[[-0.6549495   0.01610117 -0.97818309 -0.59434878 -0.53494872]
 [ 0.29317581  0.95386146 -0.10811873 -0.07155368 -0.96805977]
 [ 0.19511436 -0.93828158 -0.97131965  0.42962159  0.64358596]
 [-0.42281782 -0.86993083  0.49175428 -0.20276835  0.67690013]
 [-0.68323855 -0.18512156 -0.21775001  0.7225566  -0.30980732]]


Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [18]:
import numpy as np

array = np.random.random((3, 3))
print(array)

[[0.74608566 0.88017882 0.34604217]
 [0.80531469 0.55444562 0.05317796]
 [0.61236558 0.81317918 0.26061858]]


Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

In [19]:
import numpy as np

a = np.random.randint(1, 21, size=6)
b = np.random.randint(1, 21, size=6)

print("a =", a)
print("b =", b)
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)

a = [20  6 17 18  8 17]
b = [ 7 18 17 16  1 11]
a + b = [27 24 34 34  9 28]
a - b = [ 13 -12   0   2   7   6]
a * b = [140 108 289 288   8 187]


Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

In [20]:
import numpy as np

m1 = np.random.randint(1, 6, size=(3, 2))
m2 = np.random.randint(1, 6, size=(2, 4))

prod = m1 @ m2

print("m1:", m1)
print("m2:", m2)
print("m1 @ m2:", prod)

m1: [[3 5]
 [2 5]
 [5 5]]
m2: [[1 2 3 4]
 [2 1 1 1]]
m1 @ m2: [[13 11 14 17]
 [12  9 11 13]
 [15 15 20 25]]


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [21]:
import numpy as np

m = np.random.random((3, 3))
mt = m.T

print("m:", m)
print("m.T:", mt)

m: [[0.0326612  0.40752161 0.36037411]
 [0.04965071 0.23106434 0.5311103 ]
 [0.12370769 0.33295679 0.96095321]]
m.T: [[0.0326612  0.04965071 0.12370769]
 [0.40752161 0.23106434 0.33295679]
 [0.36037411 0.5311103  0.96095321]]


Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [22]:
import numpy as np

x = np.random.randint(1, 11, size=(3, 3))
y = np.random.randint(1, 11, size=(3, 3))

diff = x - y

print("x:", x)
print("y:", y)
print("x - y:", diff)

x: [[ 1  7  3]
 [ 4 10  5]
 [ 9  1  1]]
y: [[ 1  5 10]
 [ 3  4 10]
 [ 4  6  3]]
x - y: [[ 0  2 -7]
 [ 1  6 -5]
 [ 5 -5 -2]]


Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.

In [23]:
import numpy as np

m1 = np.random.randint(-5, 6, size=(3, 3))
m2 = np.random.randint(-5, 6, size=(3, 3))

elem_prod = m1 * m2

print("m1:", m1)
print("m2:", m2)
print("m1 * m2:", elem_prod)

m1: [[-4 -2  3]
 [ 5 -2  5]
 [ 5  5 -4]]
m2: [[-4  0  0]
 [-4  1 -1]
 [ 3 -2  3]]
m1 * m2: [[ 16   0   0]
 [-20  -2  -5]
 [ 15 -10 -12]]


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [24]:
import numpy as np

m = np.random.uniform(-1, 1, size=(3, 3))
row_sums_col = m.sum(axis=1).reshape(-1, 1)

print("m:", m)
print("row sums:", row_sums_col)

m: [[ 0.72711664 -0.22008141 -0.46775544]
 [ 0.99759224 -0.22195655 -0.81783642]
 [ 0.76224844 -0.84298653  0.71494274]]
row sums: [[ 0.03927979]
 [-0.04220073]
 [ 0.63420465]]
